---
name: Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, closed ]

jobs:
  # build:
  #   # if: github.event.pull_request.merged == false
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Build Docker image
  #       run: docker build . --file Dockerfile

  publish:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: jvoss/syslog-loki-forwarder/syslog-loki-forwarder
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: latest
